---
title: Vanderbilt Digital Humanities Center
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    layout: page
- scope:
    path: _posts
  values:
    layout: post
- scope:
    path: _drafts
  values:
    layout: post
description: Home for all things digital humanities at Vanderbilt University
owner:
  name: Vanderbilt Digital Humanities Center
  email: solanisrp2@gmail.com
  url: https://prashantsolanki.com
first_published: 2016
baseurl: ''
url: https://prashantsolanki.com
greeting:
  title: Welcome!
  text: Thanks for dropping by. I hope that it will not waste your time, but in case
    it does, at least I tried. Originally from New Delhi, India, I’m doing my B.Tech
    in Computer Science from GGSIP University. But, apart from that, I’m a die hard
    classic rock fan, coffee addict, who also enjoy messing with hardware, playing
    football and Lawn Tennis. In general, my mind can zone out during any form of
    creative act. Opinions expressed here are mine.
features-title: Intersting Stuff
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!
navlinks: bottom
works_in_progress: true
social:
  github: http://github.prashantsolanki.com/
  linkedin-square: http://linkedin.prashantsolanki.com/
  google-plus-square: http://googleplus.prashantsolanki.com/
  facebook-official: http://facebook.prashantsolanki.com/
  email: "/contact/"
permalink: "/:categories/:title"
markdown: kramdown
exclude:
- site.bat
include:
- _pages
- ".htaccess"
empty_array: []
